version: '3'
#version: '3.4'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: vue-web
  php:
    build:
      context: ./docker/php/. 
    volumes:
      - ./code:/code
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
        MYSQL_USER: test 
        MYSQL_PASSWORD: test 
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: test 
      MYSQL_DATABASE: business_db 
      MYSQL_USER: test 
      MYSQL_PASSWORD: test 