version: '3'
#version: '3.4'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test 
      MYSQL_DATABASE: business_db 
      MYSQL_USER: test 
      MYSQL_PASSWORD: test 
  node:
    build:
      context: ./code/node/. 
    volumes:
      - ./code/node:/usr/src/app
    ports:
       - 50000:50000
    depends_on:
      - mysql
    environment:
      # has to be the same as on right side of 'ports'
      PORT: 50000
      HOST: '0.0.0.0'
      MYSQL_DATABASE: business_db 
  vue:
    build:
      context: ./code/vue/.
    ports:
      - 8081:8080
    depends_on:
      - node
    volumes:
      - ./code/vue:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
